#!/usr/bin/env python3
"""Regenerate firmware/include/config.example.h from firmware/src/config.h.

Why this exists (D30). `config.h` is gitignored and per-machine, so a macro
deleted from it is invisible to git and invisible to review -- it shows up only
as a compile error, on one laptop, possibly days later. On 17 Sep nine macros
were dropped from `config.h` while `main.cpp` and `speech.cpp` still used them.
The build failed, which meant the previous image stayed on the board, which
meant the device looked like it had dead buttons. That cost a session.

The template is the only committed record of which settings exist, so it must
never lag the real file. Generating it removes the chance to forget.

    python tools/sync_config_template.py            # write the template
    python tools/sync_config_template.py --check    # CI / pre-commit: verify

--check exits 1 if the template is out of date, and prints which macros differ.
"""

import argparse
import io
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIVE = os.path.join(REPO, 'firmware', 'src', 'config.h')
TEMPLATE = os.path.join(REPO, 'firmware', 'include', 'config.example.h')

HEADER = """// config.example.h -- THE COMMITTED TEMPLATE. Copy it, then fill it in.
//
//   cp firmware/include/config.example.h firmware/src/config.h
//
// GENERATED by tools/sync_config_template.py from firmware/src/config.h.
// Do not hand-edit: edit config.h and re-run the script, or your change is
// lost the next time anyone runs it.
//
// firmware/src/config.h is gitignored and per-machine, so this file is the
// only committed record of which settings exist. If they drift, a macro can
// vanish from every laptop's build but no diff (D30).
"""

# Anything that is a credential, or specific to one machine or one network.
SCRUB = [
    (r'(#define WIFI_SSID_1\s+)"[^"]*"', r'\1"your-2.4GHz-ssid"'),
    (r'(#define WIFI_PASS_1\s+)"[^"]*"', r'\1"your-password"'),
    (r'(#define WIFI_SSID_2\s+)"[^"]*"', r'\1"fallback-hotspot"'),
    (r'(#define WIFI_PASS_2\s+)"[^"]*"', r'\1"fallback-password"'),
    (r'(#define SERVER_BASE_URL\s+)"[^"]*"', r'\1"http://192.168.1.100:5148"'),
]

# Notes that read as a log entry in config.h but need to read as an
# instruction in a file someone is about to fill in.
ANNOTATE = [
    ("// This address is a DHCP lease.",
     "// PUT THE SERVER MACHINE'S LAN IP HERE -- never localhost and never\n"
     "// 127.0.0.1, neither of which the ESP32 can reach.\n"
     "//\n"
     "// This address is a DHCP lease."),
]


def macros(text):
    return sorted(set(re.findall(r'^#define\s+([A-Za-z_][A-Za-z_0-9]*)',
                                 text, re.M)))


def render():
    live = io.open(LIVE, encoding='utf-8').read()

    # Everything above `#pragma once` is this file's own preamble, which
    # differs between the two by design.
    body = live[live.index('#pragma once'):]
    out = HEADER + body

    for pattern, replacement in SCRUB:
        out, n = re.subn(pattern, replacement, out, count=1)
        if n != 1:
            sys.exit('sync_config_template: no match for %s -- did the macro '
                     'get renamed?' % pattern)

    for old, new in ANNOTATE:
        if old in out:
            out = out.replace(old, new, 1)

    return live, out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='verify only; exit 1 if the template is stale')
    args = ap.parse_args()

    live, generated = render()

    # The macro sets matching is the property that actually matters -- a
    # missing one is what breaks the build.
    live_macros = macros(live)
    tpl_macros = macros(generated)
    if live_macros != tpl_macros:
        sys.exit('sync_config_template: macro sets differ, which should be '
                 'impossible when generating from the live file')

    current = ''
    if os.path.exists(TEMPLATE):
        current = io.open(TEMPLATE, encoding='utf-8').read()

    if args.check:
        if current != generated:
            missing = set(live_macros) - set(macros(current))
            extra = set(macros(current)) - set(live_macros)
            print('config.example.h is OUT OF DATE.')
            if missing:
                print('  in config.h, missing from the template:',
                      ', '.join(sorted(missing)))
            if extra:
                print('  in the template, gone from config.h:',
                      ', '.join(sorted(extra)))
            print('  fix: python tools/sync_config_template.py')
            return 1
        print('config.example.h is in step with config.h (%d macros).'
              % len(live_macros))
        return 0

    if current == generated:
        print('config.example.h already in step (%d macros).' % len(live_macros))
        return 0

    io.open(TEMPLATE, 'w', encoding='utf-8', newline='\n').write(generated)
    print('wrote firmware/include/config.example.h (%d macros).'
          % len(live_macros))
    return 0


if __name__ == '__main__':
    sys.exit(main())
